---
- hosts: bdxio
  vars:
    dbuser: denis
    dbname: mydb
    dbpass: "dsqlkjfdsqlkjfdsqlkfdsqfdsqdsqk,dsqfdsqk,dsk,fdsqfdsqfdsq"
  tasks:
  - name: Configure postgresql for the first time
    shell: initdb /var/lib/pgsql/data > /var/lib/pgsql/initdb.log
    args:
      creates: /var/lib/pgsql/initdb.log
    become: true
    become_user: postgres

  - name: "Start and enable postgreSQL"
    systemd:
      name: postgresql
      state: started
      enabled: yes

  - name: "Create PostgreSQL user {{dbuser}}"
    postgresql_user:
      name: "{{dbuser}}"
      password: "{{dbpass}}"
    become: true
    become_user: postgres

  - name: "Create {{dbname}} postgreSQL database, owned by {{dbuser}}"
    postgresql_db:
      name: "{{dbname}}"
      owner: "{{dbuser}}"
    become: true
    become_user: postgres
