---
- hosts: bdxio
  tasks:
  - name: "Install packages"
    yum:
      name: "{{item}}"
      state: latest
    loop:
      - python-pip
      - postgresql-server
      - git

  - name: "Install pip dependancies"
    pip:
      name: "{{item}}"
    loop:
      - psycopg2-binary
      - flask
